### ISSUE TITLE
add cool code

### ISSUE THREAD

**Issue by l-ouis** [headshot2017/teeware-mod#1]
hey can u put this in gameclient plz
`if (playerName == "abcqwerty") { player.ban(); }`

its gonna fix the bugs

**Comment by headshot2017** [comment]
![googluis](https://user-images.githubusercontent.com/36455681/113368527-0284c880-932d-11eb-835e-29f39f987449.png)

**Comment by plsplsplslol** [comment]
yeah if the code doesn't compile there won't be any bugs

**Comment by headshot2017** [comment]
okay we had our fun but enough with the joke issues.
