### ISSUE TITLE
Spectating after round win gives points

### ISSUE THREAD

**Issue by bretonium** [headshot2017/teeware-mod#12]
Steps to reproduce:

1. Win in round 1
2. Join spectators **before the next round begins**
3. Wait until round 20
4. Join the game while round 20 is in progress

Expected:
You have 1 or 0 points

Actual:
You have 19 points, and regardless of 20th round result you get a win and 24 points in the end, even if the ball throwing minigame is a draw. (and then kicked by angry players who hate you)

Notes:
Round 20 should be "ball passing" round, i am not sure that the bug is reproducible on the ninja round.

**Comment by bretonium** [comment]
There is a modification of this bug. If you lose round 1, you can win on round 2 and join spectators. Then you will have 18 and 23 points correspondingly in the end

**Comment by bretonium** [comment]
Actually, i think this bug has already been fixed, but the server admin has not updated their server (185.53.129.243:8305)

**Comment by headshot2017** [comment]
3118587 you can no longer join mid-minigame, also sounds similar to #10 which also has been corrected
