### ISSUE TITLE
kick voting is being abused

### ISSUE THREAD

**Issue by bretonium** [headshot2017/teeware-mod#13]
Players abuse the votes like on the screenshot.

Kickban votes should be disabled or should start after several accusations. 

There is an example implementation for several accusations here - https://github.com/InfectionDust/teeworlds-infclassR/blob/production/src/engine/server/server.cpp#L4737

![Screenshot_20210409_230210](https://user-images.githubusercontent.com/1087672/114240588-0a291a80-9988-11eb-94b8-72d441d8e3cd.png)

**Comment by headshot2017** [comment]
in case of bots, 287cad7 implements a basic antibot from nobyfng that checks client version and player flags.
in case of afk players, a 2 minute delay is enabled by default

an accusation system may be implemented at a later time
