### ISSUE TITLE
default rcon password in autoexec_server.cfg

### ISSUE THREAD

**Issue by def-** [headshot2017/teeware-mod#5]
there should be no default pw, otherwise the default config is insecure, can be used to read out /etc/shadow and so on.

**Comment by kamillentee** [comment]
@def- I don't understand how you could read out /etc/shadow with that? Can you explain further

**Comment by def-** [comment]
Something like `exec /etc/shadow` and then read the error messages that tell you the content. Might also have to do `exec ../../etc/shadow` or something like that and we might be blocking that in some other ways. But still not a good way to have an insecure rcon pw.
