### ISSUE TITLE
Server hangs at some point, can't connect to it anymore, but it's still running

### ISSUE THREAD

**Issue by def-** [headshot2017/teeware-mod#9]
Didn't crash, so not sure why. But I don't see the server in server browser anymore and can't connect. Logs show nothing suspicious.

**Comment by headshot2017** [comment]
did this happen when a minigame was about to start? i may have a hunch what caused it

**Comment by def-** [comment]
Based on the log after everyone left the server.

**Comment by headshot2017** [comment]
the only instance this happened to me was with the math minigame, 0fc4ccf
but not sure if it's related to this since according to your logs no one was playing

**Comment by def-** [comment]
Haven't seen in again.
